### ISSUE TITLE
roadmap to alpha

### ISSUE THREAD

**Issue by NathanVosburg** [james-bern/CS3XX#21]
absolutely necessary for alpha
- [ ] buttons 
- [ ] fillet
  - [ ] arc line fillet
  - [ ] arc arc fillet
  - [ ]  centered box
  - [ ]  power fillet
- [ ] revolve add (with angles other than 360)
- [ ] remove nathan's wonderful perfect pane
- [ ] save dxf
- [ ] some way of cleaning a drawing (ideally, automatically)
  - [ ] overlapping entities
  - [ ] zero length entities (destroyed automatically, with a warning for US, a development warning)
- [ ] a cool animated gif that pitches the product
  - [ ] a 
  - [ ] a link 
  - [ ] show the ENTIRE pipeline, including bringing into bambu studio, slicing, printing, ...
- [ ] a website
  - [ ] a logo
  - [ ] >= 5 youtube tutorials (1 for sketching, 1 for extruding, 1 for revolving)
  - [ ] download link for windows
  - [ ] download link for mac
  - [ ] download link for linux
- [ ] usability testing
  - [ ] find testers (CS136 students?)
---
???
- [ ] undo is very slow if you click on the 3D mesh a bunch
- [ ] angles in turns
- [ ] uber shader
- [ ] single entity circles
- [ ] better font
---
absolutely unnecessary for alpha
- [ ] native open and save file dialogues
- [ ] dog ear
- [ ] power dog ear
- [ ] select connected is straight up horrifying
- [ ] scary Map implementation

**Comment by NathanVosburg** [comment]
moved some stuff to #33
